# Generated by Django 4.1.4 on 2022-12-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
    ]
