# Generated by Django 4.1.4 on 2022-12-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_image_recipe_summary_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
