# Generated by Django 4.1.4 on 2022-12-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
