# Generated by Django 4.1.4 on 2022-12-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipe_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
