# Generated by Django 4.1.5 on 2023-01-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recipe_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipeID',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
