# Generated by Django 4.1.4 on 2022-12-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recipe_summar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='summar',
            new_name='summary',
        ),
    ]
