# Generated by Django 4.1.5 on 2023-01-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_ingredient_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_list',
        ),
    ]
