# Generated by Django 4.1.5 on 2023-01-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_recipe_ingredient_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='summary',
        ),
    ]
